import {
  BabyProfile,
  Caregiver,
  MilkBatch,
  MilkTransaction,
  FeedingRecord,
  PumpingRecord,
  DiaperRecord,
  DiscomfortRecord,
  WeightRecord,
  SleepRecord,
  FeedingPlanPhase,
  AuditLogEntry,
  AiInsight,
} from '../types';

export const INITIAL_CAREGIVERS: Caregiver[] = [
  { id: 'usr_1', name: 'Maria (Mãe)', role: 'mae', avatarColor: '#ec4899' },
  { id: 'usr_2', name: 'João (Pai)', role: 'pai', avatarColor: '#3b82f6' },
  { id: 'usr_3', name: 'Dra. Patrícia (Pediatra)', role: 'cuidador', avatarColor: '#10b981' },
];

export const INITIAL_BABY: BabyProfile = {
  id: 'baby_1',
  familyId: 'fam_demo',
  createdBy: 'usr_1',
  name: 'Gabriel',
  birthDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(), // 18 dias de vida
  gender: 'masculino',
  birthWeight: 3045, // 3,045 kg
  currentWeight: 3210, // 3,210 kg
  birthLength: 49,
  currentLength: 51.5,
  headCircumference: 35.2,
  bloodType: 'A+',
  notes: 'Parto normal a termo (39s+2d). Amamentação com apoio de ordenha domiciliar.',
};

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const INITIAL_FEEDING_PHASES: FeedingPlanPhase[] = [
  {
    id: 'phase_1',
    phaseNumber: 1,
    title: 'Fase Inicial Neonatal',
    targetVolumeMl: 40,
    intervalHours: 3,
    startDate: daysAgo(18),
    endDate: daysAgo(4),
    prescribedBy: 'pediatra',
    notes: 'Início pós-alta maternidade, livre demanda com intervalo máx de 3 horas.',
    isActive: false,
  },
  {
    id: 'phase_2',
    phaseNumber: 2,
    title: 'Fase 2 — Adaptação e Crescimento',
    targetVolumeMl: 55,
    intervalHours: 3,
    startDate: daysAgo(4),
    prescribedBy: 'pediatra',
    notes: 'Volume alvo ajustado após ganho ponderal satisfatório de 30g/dia.',
    isActive: true,
  },
];

export const INITIAL_BATCHES: MilkBatch[] = [
  {
    id: 'LOTE-0284',
    containerNumber: '4',
    containerName: 'Pote 4',
    containerColor: '#3b82f6',
    containerTag: 'Fresco',
    createdAt: hoursAgo(4),
    extractedAt: hoursAgo(4),
    expiresAt: new Date(now.getTime() + 8 * 60 * 60 * 1000).toISOString(), // Vence em 8h na geladeira
    originalVolumeMl: 75,
    currentVolumeMl: 75,
    location: 'geladeira',
    subLocation: 'Prateleira superior central',
    status: 'geladeira',
    protocolId: 'brasil_ms',
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
    notes: 'Coleta matinal após mamada.',
    sideDistribution: { left: 40, right: 35 },
  },
  {
    id: 'LOTE-0285',
    containerNumber: '1',
    containerName: 'Mamadeira Avent 1',
    containerColor: '#10b981',
    containerTag: 'Colostro',
    createdAt: hoursAgo(1),
    extractedAt: hoursAgo(1),
    expiresAt: new Date(now.getTime() + 11 * 60 * 60 * 1000).toISOString(), // Vence em 11h
    originalVolumeMl: 90,
    currentVolumeMl: 90,
    location: 'geladeira',
    subLocation: 'Prateleira superior',
    status: 'geladeira',
    protocolId: 'brasil_ms',
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
    notes: 'Bomba elétrica dupla, ótimo fluxo.',
    sideDistribution: { left: 50, right: 40 },
  },
  {
    id: 'LOTE-0280',
    containerNumber: '2',
    containerName: 'Pote Vidro Tampa Azul',
    containerColor: '#8b5cf6',
    containerTag: 'Leite da Noite / Madrugada',
    createdAt: daysAgo(3),
    extractedAt: daysAgo(3),
    expiresAt: new Date(now.getTime() + 12 * 24 * 60 * 60 * 1000).toISOString(), // 12 dias no freezer
    originalVolumeMl: 120,
    currentVolumeMl: 120,
    location: 'freezer',
    subLocation: 'Gaveta 1 freezer principal',
    status: 'freezer',
    protocolId: 'brasil_ms',
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
    notes: 'Frasco de vidro esterilizado tampa plástica.',
  },
  {
    id: 'LOTE-0279',
    containerNumber: '3',
    containerName: 'Pote 3',
    containerColor: '#f59e0b',
    containerTag: 'Leite Posterior (Gordura)',
    createdAt: daysAgo(5),
    extractedAt: daysAgo(5),
    expiresAt: new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    originalVolumeMl: 110,
    currentVolumeMl: 110,
    location: 'freezer',
    subLocation: 'Gaveta 1',
    status: 'freezer',
    protocolId: 'brasil_ms',
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
  },
  {
    id: 'LOTE-0275',
    containerNumber: '5',
    containerName: 'Pote 5',
    containerColor: '#ec4899',
    containerTag: 'Reserva Creche',
    createdAt: daysAgo(7),
    extractedAt: daysAgo(7),
    expiresAt: new Date(now.getTime() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    originalVolumeMl: 130,
    currentVolumeMl: 130,
    location: 'freezer',
    subLocation: 'Gaveta 2',
    status: 'freezer',
    protocolId: 'brasil_ms',
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
  },
];

export const INITIAL_TRANSACTIONS: MilkTransaction[] = [
  {
    id: 'TX-1',
    timestamp: hoursAgo(4),
    batchId: 'LOTE-0284',
    type: 'EXTRACTION',
    volumeChangeMl: 75,
    previousVolumeMl: 0,
    newVolumeMl: 75,
    toLocation: 'geladeira',
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
    reason: 'Ordenha matinal',
  },
  {
    id: 'TX-2',
    timestamp: hoursAgo(1),
    batchId: 'LOTE-0285',
    type: 'EXTRACTION',
    volumeChangeMl: 90,
    previousVolumeMl: 0,
    newVolumeMl: 90,
    toLocation: 'geladeira',
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
    reason: 'Ordenha com bomba dupla',
  },
];

export const INITIAL_FEEDINGS: FeedingRecord[] = [
  {
    id: 'feed_1',
    timestamp: hoursAgo(9),
    type: 'leite_materno_ordenhado',
    offeredMl: 45,
    consumedMl: 45,
    remainingMl: 0,
    batchIdsUsed: ['LOTE-0282'],
    caregiverId: 'usr_2',
    caregiverName: 'João (Pai)',
    notes: 'Mamada da madrugada, dormiu logo após.',
    hungerSignsBefore: true,
    satietySignsAfter: true,
    burped: true,
  },
  {
    id: 'feed_2',
    timestamp: hoursAgo(6),
    type: 'amamentacao_direta',
    durationMinutes: 22,
    directNursing: {
      leftMinutes: 12,
      rightMinutes: 10,
      lastSide: 'direito',
    },
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
    notes: 'Boa pega, esvaziamento satisfatório.',
    satietySignsAfter: true,
    burped: true,
  },
  {
    id: 'feed_3',
    timestamp: hoursAgo(3),
    type: 'leite_materno_ordenhado',
    offeredMl: 55,
    consumedMl: 50,
    remainingMl: 5,
    batchIdsUsed: ['LOTE-0283'],
    caregiverId: 'usr_2',
    caregiverName: 'João (Pai)',
    notes: 'Sobrou 5ml no copinho.',
    burped: true,
  },
  {
    id: 'feed_4',
    timestamp: hoursAgo(0.7),
    type: 'leite_materno_ordenhado',
    offeredMl: 55,
    consumedMl: 55,
    remainingMl: 0,
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
    notes: 'Mamou tudo com calma.',
    satietySignsAfter: true,
    burped: true,
  },
];

export const INITIAL_PUMPINGS: PumpingRecord[] = [
  {
    id: 'pump_1',
    timestamp: hoursAgo(4.5),
    endTime: hoursAgo(4.2),
    durationMinutes: 18,
    method: 'bomba_eletrica',
    leftVolumeMl: 40,
    rightVolumeMl: 35,
    totalVolumeMl: 75,
    targetStorage: 'geladeira',
    batchIdCreated: 'LOTE-0284',
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
    comfortLevel: 'otimo',
  },
  {
    id: 'pump_2',
    timestamp: hoursAgo(1.3),
    endTime: hoursAgo(1),
    durationMinutes: 20,
    method: 'bomba_eletrica',
    leftVolumeMl: 50,
    rightVolumeMl: 40,
    totalVolumeMl: 90,
    targetStorage: 'geladeira',
    batchIdCreated: 'LOTE-0285',
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
    comfortLevel: 'otimo',
  },
];

export const INITIAL_DIAPERS: DiaperRecord[] = [
  {
    id: 'diaper_1',
    timestamp: hoursAgo(8.5),
    hasPee: true,
    peeAmount: 'normal',
    hasPoop: true,
    poopAmount: 'normal',
    poopConsistency: 'pastoso',
    poopColor: 'mostarda',
    caregiverId: 'usr_2',
    caregiverName: 'João (Pai)',
  },
  {
    id: 'diaper_2',
    timestamp: hoursAgo(5.8),
    hasPee: true,
    peeAmount: 'muito',
    hasPoop: false,
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
  },
  {
    id: 'diaper_3',
    timestamp: hoursAgo(2.8),
    hasPee: true,
    peeAmount: 'normal',
    hasPoop: true,
    poopAmount: 'pouco',
    poopConsistency: 'pastoso',
    poopColor: 'amarelo',
    caregiverId: 'usr_2',
    caregiverName: 'João (Pai)',
  },
  {
    id: 'diaper_4',
    timestamp: hoursAgo(0.5),
    hasPee: true,
    peeAmount: 'normal',
    hasPoop: false,
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
  },
];

export const INITIAL_DISCOMFORTS: DiscomfortRecord[] = [
  {
    id: 'disc_1',
    timestamp: hoursAgo(5.2),
    durationMinutes: 15,
    symptoms: ['gases', 'irritacao'],
    intensity: 'leve',
    timing: 'logo_depois',
    reliefMeasures: ['colo', 'posicao_vertical', 'arrotar'],
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
    notes: 'Ficou em posição ereta por 10 min e arrotou.',
  },
];

export const INITIAL_SLEEP_LOGS: SleepRecord[] = [
  {
    id: 'sleep_1',
    startTime: hoursAgo(7),
    endTime: hoursAgo(4.5),
    durationMinutes: 150,
    type: 'soneca_dia',
    location: 'berco',
    quality: 'tranquilo',
    wakingReason: 'fome',
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
    notes: 'Soneca tranquila após mamada.',
  },
  {
    id: 'sleep_2',
    startTime: hoursAgo(3),
    endTime: hoursAgo(1.5),
    durationMinutes: 90,
    type: 'soneca_dia',
    location: 'colo',
    quality: 'agitado',
    wakingReason: 'espontaneo',
    caregiverId: 'usr_2',
    caregiverName: 'João (Pai)',
    notes: 'Dormiu no colo após arrotar.',
  },
];

export const INITIAL_WEIGHTS: WeightRecord[] = [
  {
    id: 'wt_1',
    timestamp: daysAgo(18),
    weightGrams: 3045,
    lengthCm: 49,
    headCircumferenceCm: 34.5,
    location: 'Hospital Maternidade',
    caregiverId: 'usr_3',
    caregiverName: 'Dra. Patrícia (Pediatra)',
    notes: 'Peso de nascimento.',
  },
  {
    id: 'wt_2',
    timestamp: daysAgo(15),
    weightGrams: 2830,
    lengthCm: 49,
    headCircumferenceCm: 34.5,
    location: 'Hospital Maternidade',
    caregiverId: 'usr_3',
    caregiverName: 'Dra. Patrícia (Pediatra)',
    notes: 'Peso de alta (perda fisiológica esperada de 7%).',
  },
  {
    id: 'wt_3',
    timestamp: daysAgo(8),
    weightGrams: 3050,
    lengthCm: 50,
    headCircumferenceCm: 34.8,
    location: 'Consultório Pediátrico',
    caregiverId: 'usr_3',
    caregiverName: 'Dra. Patrícia (Pediatra)',
    notes: 'Recuperou peso de nascimento com 10 dias.',
  },
  {
    id: 'wt_4',
    timestamp: daysAgo(1),
    weightGrams: 3210,
    lengthCm: 51.5,
    headCircumferenceCm: 35.2,
    location: 'Balança Domiciliar',
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
    notes: 'Ganho médio de ~23g/dia na última semana.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud_1',
    timestamp: hoursAgo(4),
    entityType: 'batch',
    entityId: 'LOTE-0284',
    action: 'CREATE',
    newValue: { volume: 75, location: 'geladeira' },
    caregiverId: 'usr_1',
    caregiverName: 'Maria (Mãe)',
    description: 'Criado Lote #LOTE-0284 com 75ml na Geladeira.',
  },
  {
    id: 'aud_2',
    timestamp: hoursAgo(3),
    entityType: 'feeding',
    entityId: 'feed_3',
    action: 'CREATE',
    newValue: { consumed: 50 },
    caregiverId: 'usr_2',
    caregiverName: 'João (Pai)',
    description: 'Registrada mamada de 50ml por João (Pai).',
  },
];

export const INITIAL_AI_INSIGHTS: AiInsight[] = [
  {
    id: 'ins_1',
    category: 'alimentacao',
    title: 'Consumo Estável e Adequado',
    shortText: 'O bebê realizou 4 mamadas hoje totalizando 150 ml (mais mamada ao peito de 22 min), com excelente aproveitamento.',
    confidence: 'alta',
    confidenceReason: 'Registros contínuos nas últimas 24 horas.',
    timestamp: hoursAgo(1),
  },
  {
    id: 'ins_2',
    category: 'estoque',
    title: 'Lote #LOTE-0284 com Prioridade FEFO',
    shortText: 'O lote #0284 na geladeira vence em aproximadamente 8 horas e é o recomendado para a próxima mamada.',
    confidence: 'alta',
    confidenceReason: 'Cálculo determinístico baseado no Protocolo Ministério da Saúde.',
    timestamp: hoursAgo(2),
  },
  {
    id: 'ins_3',
    category: 'crescimento',
    title: 'Curva Ponderal Positiva (+160g)',
    shortText: 'Ganho consistente de 23g/dia mantendo trajetória adequada no percentil OMS P50.',
    confidence: 'alta',
    confidenceReason: '4 pesagens registradas com datas precisas.',
    timestamp: daysAgo(1),
  },
];
